Repository WebAssemblySummit/webassembly-summit.org, pull requests merged in 2019-11, with the labels that each got.

#7 [WIP] feat(readme): add README with status badge, brief desc
  README.md
Labels: work in progress

#11 Added some contributing docs
  README.md
Labels: needs review

#12 Added Contact Us Information
  pages/index.tsx
Labels: enhancement
