Repository WebAssemblySummit/webassembly-summit.org, pull requests merged in 2020-01, with the labels that each got.

#42 Feature/37 speaker page
  components/NavBar/index.tsx
  pages/_app.tsx
  pages/about.tsx
  pages/index.tsx
  pages/speakers.tsx
Labels: PR attached, needs review

#44 update ticket faq
  pages/about.tsx
Labels: PR attached, needs review

#48 refactoring of speakers and about page
  components/Button.tsx
  components/colors.ts
  pages/_app.tsx
  pages/about.tsx
  pages/about/data.tsx
  pages/about/index.tsx
  pages/index.tsx
  pages/speakers/data.tsx
  pages/speakers/index.tsx
Labels: PR attached, needs review

#53 page title fix
  components/Header.tsx
  components/NavBar/index.tsx
  pages/about/index.tsx
  pages/speakers/data.tsx
  pages/speakers/index.tsx
Labels: PR attached, bug, needs review

#49 refined speaker deck grid layout
  components/NavBar.tsx
  pages/about/index.tsx
  pages/speakers/index.tsx
Labels: PR attached, needs review

#54 Feature/51 navigation bar refinements
  components/NavBar.tsx
  components/colors.ts
  pages/about/index.tsx
  pages/index.tsx
  pages/speakers/index.tsx
Labels: PR attached, needs review

#58 added service worker for offline support
  .github/workflows/deploy.yml
  data/about.tsx
  next.config.js
  package.json
  pages/_app.tsx
  public/manifest.json
  yarn.lock
Labels: PR attached, experimental, work in progress

#74 pwa fullscreen support + app icons
  pages/_app.tsx
  public/apple-icon-120.png
  public/apple-icon-152.png
  public/apple-icon-167.png
  public/apple-icon-180.png
  public/apple-splash-1125-2436.png
  public/apple-splash-1136-640.png
  public/apple-splash-1242-2208.png
  public/apple-splash-1242-2688.png
  public/apple-splash-1334-750.png
  public/apple-splash-1536-2048.png
  public/apple-splash-1668-2224.png
  public/apple-splash-1668-2388.png
  public/apple-splash-1792-828.png
  public/apple-splash-2048-1536.png
  public/apple-splash-2048-2732.png
  public/apple-splash-2208-1242.png
  public/apple-splash-2224-1668.png
  public/apple-splash-2388-1668.png
  public/apple-splash-2436-1125.png
  public/apple-splash-2688-1242.png
  public/apple-splash-2732-2048.png
  public/apple-splash-640-1136.png
  public/apple-splash-750-1334.png
  public/apple-splash-828-1792.png
  public/favicon-196.png
  public/manifest-icon-192.png
  public/manifest-icon-512.png
  public/manifest.json
Labels: needs review

#75 Feature/73 iphone navbar bug
  components/NavBar.tsx
  hooks/useScrollDirection.ts
Labels: needs review

#76 lighthouse referrer security problem fix
  components/NavBar.tsx
Labels: bug, needs review

#78 fixed discord link
  components/NavBar.tsx
Labels: bug, needs review

#80 Feature/56 improve faq
  data/about.tsx
  pages/about/index.tsx
Labels: needs review

#77 fixes for pwa ui glitches
  pages/_app.tsx
Labels: bug, needs review

#79 landing page layout refinements
  components/NavBar.tsx
  pages/index.tsx
Labels: enhancement, needs review

#83 link directly to #summit channel on Discord
  data/about.tsx
Labels: needs review

#84 navbar bottom margin increased only in standalone mode
  components/NavBar.tsx
Labels: enhancement, needs review

#85 landing page + about page column layout fixes
  hooks/useScrollDirection.ts
  pages/_app.tsx
  pages/about/index.tsx
  pages/index.tsx
Labels: needs review

#91 Bug/remove service worker
  next.config.js
  pages/_app.tsx
Labels: bug, needs review

#106 Added the suggested improvements from #104
  pages/schedule.tsx
Labels: bug

#107 fix for missing schedule route
  next.config.js
Labels: bug

#109 Finalized Schedule Page
  data/schedule.tsx
  pages/schedule.tsx
Labels: enhancement

#112 added youtube links
  data/about.tsx
Labels: needs review
